services:
  ros2_humble:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORKSPACE: /workspace

    image: ros2_humble_dev
    container_name: ros2_humble_new

    ports:
      - "8765:8765"

    environment:
      ROS_DISTRO: humble
      TURTLEBOT3_MODEL: burger
      ROS_DOMAIN_ID: "0"
      WORKSPACE: /workspace

    volumes:
      - .:/workspace

    command:
      - bash
      - -c
      - |
        source /opt/ros/humble/setup.bash
        ros2 run foxglove_bridge foxglove_bridge \
        --ros-args \
        -p port:=8765 \
        -p address:=0.0.0.0 \
        --params-file /workspace/config/foxglove_bridge_params.yaml
    
    stdin_open: true
    tty: true